volumes:
  mongo_data_second_node:

services:
  second_node:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    env_file: ./apps/backend/.env
    environment:
      - NODE_ENV=production
      - PORT=8081
      - MONGODB_URL=mongodb://mongo_second_node:27017/omni-index
      - MONGODB_DB=omni-index
      - FRONTEND_URL=https://example.com
    ports:
      - "8081:8081"
    depends_on:
      mongo_second_node:
        condition: service_started
  mongo_second_node:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data_second_node:/data/db
    ports:
      - "27037:27017"
