volumes:
  mongo_data_second_node:

services:
  mongo_second_node:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data_second_node:/data/db
    ports:
      - "27037:27017"
