packages:
  - apps/*
  - apps/frontends/*
  - proof-of-concept
injectWorkspacePackages: true
onlyBuiltDependencies:
  - cbor-extract
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
  - unrs-resolver
