{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.omniBook.domain | quote }}
        - {{ .Values.omniIndex.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName | default (include "helm.fullname" .) | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.omniBook.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: omni-book
                port:
                  number: 80
    - host: {{ .Values.omniIndex.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: omni-index
                port:
                  number: 80
{{- end }}
