apiVersion: v1
kind: Service
metadata:
  name: omni-book
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "helm.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
