apiVersion: batch/v1
kind: Job
metadata:
  name: omni-index-migration
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/name: omni-index
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  # must explicitly declare a selector that matches your pod labels
  selector:
    matchLabels:
      {{- include "helm.labels" . | nindent 6 }}
      app.kubernetes.io/name: omni-index
      app.kubernetes.io/component: migration

  # pod template inherits the same labels
  template:
    metadata:
      labels:
        {{- include "helm.labels" . | nindent 8 }}
        app.kubernetes.io/name: omni-index
        app.kubernetes.io/component: migration

    spec:
      containers:
        - name: migration
          image: "{{ .Values.omniIndex.migration.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_DB
              value: omni-index
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: uri
      restartPolicy: OnFailure
