{{- include "mongo.config.validate" . }}

{{- $username := .Values.mongo.credentials.user }}
{{- $password := .Values.mongo.credentials.password }}

{{- $uri := "" }}
{{- if .Values.mongo.enabled }}
  {{- $uri = (printf "mongodb://%s:%s@mongodb-0.mongodb:27017" $username $password) }}
{{- else }}
  {{- $uri = .Values.mongo.externalUri }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/name: "mongodb"
    app.kubernetes.io/component: "db"
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  uri: {{ $uri | quote }}
