{{- include "mongo.config.validate" . }}

{{- $existing := lookup "v1" "Secret" .Release.Namespace "mongodb-credentials" }}
{{- $username := .Values.mongo.credentials.user }}
{{- $password := "" }}
{{- if $existing }}
  {{- $password = (index $existing.data "mongodb-password") | b64dec }}
{{- else }}
  {{- $password = (randAlphaNum 16) }}
{{- end }}

{{- $uri := "" }}
{{- if .Values.mongo.enabled }}
  {{- $uri = (printf "mongodb://%s:%s@mongodb-0.mongodb:27017" $username $password) }}
{{- else if $existing }}
  {{- $uri = (index $existing.data "mongodb-uri") | b64dec }}
{{- else }}
  {{- $uri = .Values.mongo.externalUri }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/name: "mongodb"
    app.kubernetes.io/component: "db"
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  uri: {{ $uri | quote }}
