name: CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Pre-pull docker images
        run: |
          docker pull mongo:8
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Node
        run: |
          pnpm env -g use 22
          echo "Node version: $(node -v)"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm -r build
      - name: E2E tests
        run: pnpm -r test:e2e
  build-docker:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        image:
          - name: backend
            repo: prenaissance/omni-index
            target: runner
          - name: migration
            repo: prenaissance/omni-index-migration
            target: migration

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image ${{matrix.image.name}}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/backend/Dockerfile
          target: ${{ matrix.image.target }}
          push: false
          platforms: ${{ env.TARGET_PLATFORMS }}
          tags: ${{ matrix.image.repo }}:${{ github.sha }}
